fix: add worker/ to files field in package.json (#610)
The worker/ directory is required by apis/worker.js (require('../worker/index'))
but was omitted from the files field, causing v8.0.24 to fail at require time:

  Error: Cannot find module '../worker/index'

This breaks all dependents using ^8.x ranges.